# -------------------------------------------------------------------------------
# Site settings
# -------------------------------------------------------------------------------

title: ORCS Lab @ UFMG

author: ORCS Team
email: andre.maravilha@outlook.com

description: >-
    ORCS Lab - Operations Research and Complex Systems Lab at UFMG. Research involving optimization, computational intelligence, evolutionary computation, decision-making, statistical modeling and complex systems.

baseurl: ""
url: "https://orcslab.github.io"

github_url: https://github.com/orcslab
linkedin_url: https://www.linkedin.com/company/orcslab
researchgate_url: https://www.researchgate.net/lab/ORCS-Lab-Lucas-Batista

# -------------------------------------------------------------------------------
# Build settings
# -------------------------------------------------------------------------------

include:
  - .htaccess

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/news/:num"
